# Generated by Django 3.0.8 on 2020-08-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldnums', '0002_auto_20200802_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='recovered',
            field=models.IntegerField(null=True),
        ),
    ]
