# Generated by Django 3.0.8 on 2020-08-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldnums', '0004_auto_20200802_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='active',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='confirmed',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='deaths',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='recovered',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
